version: '3'

services:
  tortoisebot-ros1-real:
    image: miguelsolissegura/miguelsolissegura-cp22:tortoisebot-ros1-real
    container_name: tortoisebot-ros1-real
    privileged: true
    volumes:
      - /dev/mem:/dev/mem
      - /dev/vchiq:/dev/vchiq
    environment:
      - ROS_MASTER_URI=http://tortoisebot-ros1-real:11311
      - ROS_HOSTNAME=tortoisebot-ros1-real
    networks:
      - ros_network

  tortoisebot-ros1-slam-real:
    image: miguelsolissegura/miguelsolissegura-cp22:tortoisebot-ros1-slam-real
    container_name: tortoisebot-ros1-slam-real
    privileged: true
    volumes:
      - /dev/mem:/dev/mem
      - /dev/vchiq:/dev/vchiq
    environment:
      - ROS_MASTER_URI=http://tortoisebot-ros1-real:11311
      - ROS_HOSTNAME=tortoisebot-ros1-slam-real
    depends_on:
      - tortoisebot-ros1-real
    networks:
      - ros_network
    ports:
      - "11311:11311"

networks:
  ros_network:
    driver: bridge